ig.baked=true;ig.module('game.entities.trigger').requires('impact.entity','plugins.twopointfive.hud').defines(function(){EntityTrigger=ig.Entity.extend({size:{x:16,y:16},_wmScalable:true,_wmDrawBox:true,_wmBoxColor:'rgba(196, 255, 0, 0.7)',spawnEntity:false,entityName:null,target:null,triggerText:false,textValue:"",wait:-1,waitTimer:null,canFire:true,loadLevel:false,levelName:"",font:new tpf.Font('media/fredoka-one.font.png'),type:ig.Entity.TYPE.NONE,checkAgainst:ig.Entity.TYPE.A,collides:ig.Entity.COLLIDES.NEVER,init:function(x,y,settings){if(settings.checks){this.checkAgainst=ig.Entity.TYPE[settings.checks.toUpperCase()]||ig.Entity.TYPE.A;delete settings.check;}
this.parent(x,y,settings);this.waitTimer=new ig.Timer();},getRandomSpawnPos:function(){var floorMap=ig.game.floorMap;var ts=floorMap.tilesize;while(true){var x=((Math.random()*floorMap.width)|0)*ts+ts/2,y=((Math.random()*floorMap.height)|0)*ts+ts/2;if(floorMap.getTile(x,y)){return{x:x,y:y};}}},check:function(other){if(this.canFire&&this.waitTimer.delta()>=0){if(typeof(this.target)==='object'&&this.target!==null){for(var t in this.target){var ent=ig.game.getEntityByName(this.target[t]);if(ent&&typeof(ent.triggeredBy)=='function'){ent.triggeredBy(other,this);}}}else if(this.spawnEntity&&this.entityName!==null){switch(this.entityName){case"EnemyBlob":var spawnPos=null;var player=ig.game.getEntitiesByType(EntityPlayer)[0];var playerPos=player.pos;for(var i=0;i<55;i++){spawnPos=this.getRandomSpawnPos();var spawnDist=Math.abs(spawnPos.x-playerPos.x)+Math.abs(spawnPos.y-playerPos.y);if(spawnDist>256&&spawnDist<500){break;}}
ig.game.spawnEntity(EntityEnemyBlob,spawnPos.x,spawnPos.y);break;case"Zombie":var spawnPos=null;var player=ig.game.getEntitiesByType(EntityPlayer)[0];var playerPos=player.pos;for(var i=0;i<55;i++){spawnPos=this.getRandomSpawnPos();var spawnDist=Math.abs(spawnPos.x-playerPos.x)+Math.abs(spawnPos.y-playerPos.y);if(spawnDist>256&&spawnDist<500){break;}}
ig.game.spawnEntity(EntityZombie,spawnPos.x,spawnPos.y);break;case"Pixel":var spawnPos=null;var player=ig.game.getEntitiesByType(EntityPlayer)[0];var playerPos=player.pos;for(var i=0;i<55;i++){spawnPos=this.getRandomSpawnPos();var spawnDist=Math.abs(spawnPos.x-playerPos.x)+Math.abs(spawnPos.y-playerPos.y);if(spawnDist>256&&spawnDist<500){break;}}
ig.game.spawnEntity(EntityPixelmonster,spawnPos.x,spawnPos.y);break;default:break;}}
var player=ig.game.getEntitiesByType(EntityPlayer)[0]
if(this.giveWeapon==="pistol"){player.giveWeapon(WeaponPistol,32);}
if(this.giveWeapon==="shotgun"){player.giveWeapon(WeaponShotgun,12);}
if(this.giveWeapon==="grenade"){player.giveWeapon(WeaponGrenadeLauncher,6);}
if(this.loadLevel){switch(this.levelName){case"level1":ig.game.menu=new Intro1();break;case"base1":ig.game.menu=new Intro2();break;case"level3":ig.game.menu=new Intro3();break;case"level4":ig.game.menu=new Intro4();break;case"Ending":ig.game.menu=new Ending();break;default:break;}}
if(this.introText){ig.game.loadIntroText("TEST");}
if(this.wait==-1){this.canFire=false;}
else{this.waitTimer.set(this.wait);}}},update:function(){}});});